# Generated by Django 5.2.9 on 2026-01-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_popupoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='orders/pdfs/'),
        ),
    ]
